/**
 * Motion that is designed, not filtered.
 *
 * Everything else in this renderer asks ffmpeg to move pixels around. That is
 * the right tool for a push, a crop or a colour shift, and the wrong one for
 * type that arrives with weight — a word that overshoots and settles, letters
 * that stagger in, a card that lands. Those are described far more naturally in
 * HTML and CSS than in a filter expression, and CSS has an easing model that
 * `zoompan` does not.
 *
 * So a scene is a web page, and this module turns it into a transparent frame
 * sequence that the main graph lays over the video.
 *
 * **Nothing is ever played.** Every animation on the page is paused, and for
 * frame N the page is *seeked* to N/fps and screenshotted. A frame therefore
 * takes as long as it takes to paint — a second, a minute — and comes out
 * identical either way. Render the same scene twice and the bytes match, which
 * is the property that separates a motion engine from a screen recorder, and
 * the one the test asserts.
 *
 * Two mistakes are worth naming because both cost a day:
 *
 * - Playwright's `screenshot({ animations: "disabled" })` does not freeze
 *   animations, it **fast-forwards them to their end**. With time already being
 *   driven by hand it silently renders every frame as the last one.
 * - `cubic-bezier` cannot overshoot and settle, which is the whole character of
 *   a spring. So the curve is generated by sampling a damped oscillator and
 *   emitted as CSS `linear()`.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

/** Samples per output frame. Four is enough for a convincing shutter. */
export const MOTION_SUBSAMPLES = 4;

/**
 * A damped oscillator, sampled into a CSS `linear()` curve.
 *
 * `damping` is how fast it stops arguing with itself and `frequency` how many
 * times it argues. 7.2 and 10.5 give one clear overshoot and a quick settle,
 * which reads as "solid object" rather than "bouncy toy".
 */
export function spring(damping = 7.2, frequency = 10.5, samples = 60): string {
  const points: string[] = [];
  for (let i = 0; i <= samples; i += 1) {
    const t = i / samples;
    const value = 1 - Math.exp(-damping * t) * Math.cos(frequency * t);
    points.push(value.toFixed(5));
  }
  // The last sample must be exactly 1 or the element settles a hair off its
  // final position and stays there.
  points[points.length - 1] = "1";
  return `linear(${points.join(",")})`;
}

/**
 * How long between one word landing and the next, in seconds.
 *
 * Fast enough that a three-word line is finished in a third of a second, slow
 * enough that the eye catches each arrival. Under about 60 ms the stagger stops
 * reading as a sequence and starts reading as a wobble in a single block.
 */
const STAGGER_S = 0.11;

/**
 * The pieces a kinetic line arrives in.
 *
 * Whitespace, and nothing cleverer. Splitting on characters would animate
 * Arabic letter by letter, which breaks shaping — the letters are joined, and
 * a joined script pulled apart is a different word. Splitting on punctuation
 * would strand a comma on its own line. A word is what a reader tracks, so a
 * word is the unit.
 */
export function wordsOf(text: string): string[] {
  return text.trim().split(/\s+/).filter((word) => word.length > 0);
}

export interface MotionTitle {
  text: string;
  /** Seconds on the *output* clock. The caller has already remapped it. */
  at: number;
  durationSeconds: number;
  style: "card" | "lower-third" | "word";
  position: "top" | "center" | "bottom";
}

export interface MotionSceneOptions {
  width: number;
  height: number;
  fps: number;
  titles: MotionTitle[];
  /** Total length of the layer, in seconds. */
  durationSeconds: number;
}

const PLACEMENT: Record<MotionTitle["position"], string> = {
  top: "align-items:flex-start;padding-top:12%",
  center: "align-items:center",
  bottom: "align-items:flex-end;padding-bottom:18%",
};

/**
 * The scene, as a self-contained page.
 *
 * Written as one document with one animation per title rather than a timeline
 * abstraction: the browser already has a timeline, and every layer of
 * indirection over it is a layer that can disagree with what is drawn.
 */
export function sceneHtml(options: MotionSceneOptions): string {
  const { width, height, titles } = options;
  const curve = spring();

  const blocks = titles
    .map((title, index) => {
      const cls = `t${index}`;
      const size = title.style === "card" ? 0.11 : title.style === "lower-third" ? 0.062 : 0.135;
      const weight = title.style === "word" ? 900 : 800;
      // Escaped here rather than trusted: a title is user text, and a page is a
      // place where user text becomes markup if nobody stops it.
      const escape = (value: string) =>
        value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
      const safe = escape(title.text);
      const rise = Math.round(height * 0.05);

      /**
       * The kinetic style, which until this round was not kinetic.
       *
       * `word` is documented — in the schema, and in the instructions the model
       * reads — as words arriving on the screen. It rendered the whole string
       * as one block with the same curve as a card, so a three-word line
       * landed as a slab. Nothing failed: the frames had ink on them, the
       * export played, and the only thing wrong was that the feature named
       * after words did not treat them as words. That is this codebase's
       * oldest enemy, and it had been sitting inside the one operation whose
       * entire purpose is to be *seen*.
       *
       * Each word is an inline-block, which matters for more than the
       * transform it needs: an atomic inline is neutral to the bidi algorithm,
       * so a run of them is laid out in the paragraph's own direction. The
       * first word of an Arabic line therefore lands on the **right**, and the
       * first word of an English line on the left, with no direction logic
       * here at all — the same reason `dir="auto"` is on the span rather than a
       * rule we wrote ourselves.
       */
      const pieces = title.style === "word" ? wordsOf(title.text) : [];
      const kinetic = pieces.length > 1;
      /**
       * Every word must be on screen while the title still is.
       *
       * A fixed stagger is fine for three words and wrong for twelve: at 0.11 s
       * a twelve-word line is still arriving 1.2 s in, and a two-second title
       * begins fading before its last word has landed — a word nobody ever
       * reads, in a file nobody re-renders. So the stagger compresses until the
       * final word arrives no later than halfway through the title's life.
       */
      const stagger = kinetic
        ? Math.min(STAGGER_S, (title.durationSeconds * 0.5) / (pieces.length - 1))
        : 0;

      const shared = `
        .${cls} {
          position:absolute; inset:0; display:flex; justify-content:center;
          ${PLACEMENT[title.position]};
        }
        .${cls} span {
          font: ${weight} ${Math.round(height * size)}px/1.1 Inter, "DejaVu Sans", system-ui, sans-serif;
          color:#fff; text-align:center; max-width:82%;
          letter-spacing:-0.02em;
          text-shadow: 0 ${Math.round(height * 0.004)}px ${Math.round(height * 0.012)}px rgba(0,0,0,.55);
        }
        @keyframes out-${cls} { to { opacity:0 } }`;

      if (kinetic) {
        return {
          css: `${shared}
        .${cls} {
          opacity:1;
          animation: out-${cls} 320ms ease-in ${(title.at + title.durationSeconds).toFixed(3)}s forwards;
        }
        .${cls} i {
          font-style:normal; display:inline-block; opacity:0;
          transform: translateY(${rise}px) scale(.86);
          animation: word-in 620ms ${curve} forwards;
        }`,
          html: `<div class="${cls}"><span dir="auto">${pieces
            .map(
              (word, w) =>
                `<i style="animation-delay:${(title.at + w * stagger).toFixed(3)}s">${escape(word)}</i>`,
            )
            .join(" ")}</span></div>`,
        };
      }

      return {
        css: `${shared}
        .${cls} {
          opacity:0;
          animation: in-${cls} 620ms ${curve} ${title.at}s forwards,
                     out-${cls} 320ms ease-in ${(title.at + title.durationSeconds).toFixed(3)}s forwards;
        }
        .${cls} span {
          transform: translateY(${rise}px) scale(.94);
          animation: rise-${cls} 620ms ${curve} ${title.at}s forwards;
        }
        @keyframes in-${cls} { to { opacity:1 } }
        @keyframes rise-${cls} { to { transform: translateY(0) scale(1) } }`,
        // `dir="auto"` for the same reason the editor carries it, and with more
        // at stake: a title is *burned into the file*. The browser reads the
        // first strong character and lays the line out that way, so an Arabic
        // title's question mark ends the sentence instead of opening it, and an
        // English title is laid out exactly as it was before. Measured, not
        // assumed: without it the bang in «٥ أسرار للنجاح!» sits four fifths of
        // the way across the line — at the wrong end, permanently.
        html: `<div class="${cls}"><span dir="auto">${safe}</span></div>`,
      };
    });

  return `<!doctype html><html><head><meta charset="utf-8"><style>
  html,body { margin:0; padding:0; width:${width}px; height:${height}px; background:transparent; overflow:hidden }
  @keyframes word-in { to { opacity:1; transform: translateY(0) scale(1) } }
  ${blocks.map((b) => b.css).join("\n")}
  </style></head><body>${blocks.map((b) => b.html).join("")}</body></html>`;
}

export interface MotionLayer {
  /** ffmpeg input pattern for the frame sequence, e.g. `/tmp/x/m%06d.png`. */
  pattern: string;
  frames: number;
  fps: number;
}

/**
 * Render the scene to a transparent PNG sequence.
 *
 * Returns `null` when no browser is available, which is a real case — the
 * worker image carries one, a laptop running the suite may not — and a missing
 * browser must cost the titles, not the render.
 */
/**
 * The parts of Playwright and of the page we actually touch.
 *
 * Written out rather than imported for the reason above, and kept deliberately
 * narrow: this is the contract this file depends on, and a change to any of it
 * should be a compile error rather than a black screen in an export.
 */
interface ChromiumLike {
  launch(options: { executablePath?: string; args: string[] }): Promise<BrowserLike>;
}
interface BrowserLike {
  newPage(options: {
    viewport: { width: number; height: number };
    deviceScaleFactor: number;
  }): Promise<PageLike>;
  close(): Promise<void>;
}
interface PageLike {
  goto(url: string, options: { waitUntil: "load" }): Promise<unknown>;
  evaluate<A>(fn: (arg: A) => unknown, arg?: A): Promise<unknown>;
  screenshot(options: { path: string; omitBackground: boolean }): Promise<unknown>;
  close(): Promise<void>;
}

/**
 * `document` inside a page.evaluate callback is Chromium's, not Node's. Only
 * the two members these callbacks use are declared, which is also the shortest
 * possible statement of what the animation capture depends on.
 */
declare const document: {
  fonts: { ready: Promise<unknown> };
  getAnimations(): Array<{ pause(): void; currentTime: number | null }>;
};

export async function renderMotionLayer(
  options: MotionSceneOptions,
  outDir: string,
): Promise<MotionLayer | null> {
  // playwright-core is deliberately not a dependency of this package: it is
  // installed into the runtime image (see the Dockerfile) and marked external
  // in the bundle, because a laptop running the test suite should not have to
  // download a browser driver to typecheck a video encoder. That means there
  // are no types for it here, and the specifier is held in a variable so the
  // compiler does not try to resolve one.
  // Two names for the same driver. The runtime image installs `playwright-core`
  // because it is the smaller of the two and downloads no browsers; a machine
  // that has run the test suite usually has the full `playwright` instead. Both
  // export the same `chromium`, so trying them in order is the difference
  // between titles that render everywhere and titles that render in production
  // only — where nobody can see them fail.
  let chromium: ChromiumLike | null = null;
  for (const specifier of ["playwright-core", "playwright"]) {
    try {
      const mod = (await import(specifier)) as { chromium?: ChromiumLike };
      if (mod.chromium) {
        chromium = mod.chromium;
        break;
      }
    } catch {
      // Not installed under that name. Try the other.
    }
  }
  if (!chromium) return null;

  /**
   * Where the browser is — or, usually, not saying.
   *
   * The runtime image installs Chromium from the distribution and points
   * CHROMIUM_PATH at it, because playwright-core ships no browser of its own.
   * Everywhere else — a CI runner after `playwright install`, a laptop —
   * Playwright already knows where its own build lives, and naming a path it
   * does not have is how the whole feature silently turns itself off. So the
   * path is passed only when it was actually configured.
   */
  const executablePath = process.env["CHROMIUM_PATH"]?.trim();
  let browser;
  try {
    browser = await chromium.launch({
      ...(executablePath ? { executablePath } : {}),
      args: ["--no-sandbox", "--force-color-profile=srgb", "--disable-lcd-text"],
    });
  } catch {
    return null;
  }

  try {
    await mkdir(outDir, { recursive: true });
    const html = path.join(outDir, "scene.html");
    await writeFile(html, sceneHtml(options), "utf8");

    const page = await browser.newPage({
      viewport: { width: options.width, height: options.height },
      deviceScaleFactor: 1,
    });
    await page.goto(`file://${html}`, { waitUntil: "load" });
    // Fonts must resolve before the first frame or frame 0 renders in a
    // fallback face and every later frame renders in the real one — a seam
    // nobody would guess at from the code.
    await page.evaluate(() => document.fonts.ready);

    const sampleRate = options.fps * MOTION_SUBSAMPLES;
    const total = Math.ceil(options.durationSeconds * sampleRate);
    for (let i = 0; i < total; i += 1) {
      const timeMs = (i / sampleRate) * 1000;
      await page.evaluate((t) => {
        for (const animation of document.getAnimations()) {
          animation.pause();
          animation.currentTime = t;
        }
      }, timeMs);
      await page.screenshot({
        path: path.join(outDir, `m${String(i).padStart(6, "0")}.png`),
        omitBackground: true,
      });
    }
    await page.close();
    return { pattern: path.join(outDir, "m%06d.png"), frames: total, fps: sampleRate };
  } catch {
    return null;
  } finally {
    await browser.close().catch(() => {});
  }
}
