/**
 * Motion that is designed, not filtered.
 *
 * Everything else in this renderer asks ffmpeg to move pixels around. That is
 * the right tool for a push, a crop or a colour shift, and the wrong one for
 * type that arrives with weight — a word that overshoots and settles, letters
 * that stagger in, a card that lands. Those are described far more naturally in
 * HTML and CSS than in a filter expression, and CSS has an easing model that
 * `zoompan` does not.
 *
 * So a scene is a web page, and this module turns it into a transparent frame
 * sequence that the main graph lays over the video.
 *
 * **Nothing is ever played.** Every animation on the page is paused, and for
 * frame N the page is *seeked* to N/fps and screenshotted. A frame therefore
 * takes as long as it takes to paint — a second, a minute — and comes out
 * identical either way. Render the same scene twice and the bytes match, which
 * is the property that separates a motion engine from a screen recorder, and
 * the one the test asserts.
 *
 * Two mistakes are worth naming because both cost a day:
 *
 * - Playwright's `screenshot({ animations: "disabled" })` does not freeze
 *   animations, it **fast-forwards them to their end**. With time already being
 *   driven by hand it silently renders every frame as the last one.
 * - `cubic-bezier` cannot overshoot and settle, which is the whole character of
 *   a spring. So the curve is generated by sampling a damped oscillator and
 *   emitted as CSS `linear()`.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

/** Samples per output frame. Four is enough for a convincing shutter. */
export const MOTION_SUBSAMPLES = 4;

/**
 * A damped oscillator, sampled into a CSS `linear()` curve.
 *
 * `damping` is how fast it stops arguing with itself and `frequency` how many
 * times it argues. 7.2 and 10.5 give one clear overshoot and a quick settle,
 * which reads as "solid object" rather than "bouncy toy".
 */
export function spring(damping = 7.2, frequency = 10.5, samples = 60): string {
  const points: string[] = [];
  for (let i = 0; i <= samples; i += 1) {
    const t = i / samples;
    const value = 1 - Math.exp(-damping * t) * Math.cos(frequency * t);
    points.push(value.toFixed(5));
  }
  // The last sample must be exactly 1 or the element settles a hair off its
  // final position and stays there.
  points[points.length - 1] = "1";
  return `linear(${points.join(",")})`;
}

/* ────────────────────────────────────────────────────────────────────────────
   The vocabulary
   ────────────────────────────────────────────────────────────────────────────

   Four things separate motion that reads as designed from motion that reads as
   a template, and the reference study put them above any single effect: a fast
   entrance that overshoots and settles, a stagger so nothing arrives all at
   once, a large soft shadow so things look lifted rather than pasted, and
   placement measured against the frame rather than against whatever box the
   element happens to sit in.

   All four already existed here — inside the title renderer, written inline,
   reachable by nothing else. That was fine while text was the only thing this
   engine drew. It is the whole problem now: an interstitial card, a device
   mockup and an overlay diagram each need the same four, and a vocabulary that
   has to be re-typed per element is a vocabulary that drifts per element. The
   spring in one place and an ease in another is exactly how a set of features
   built by the same hands stops looking like one product.

   So they are named here, once, and the title renderer below is simply the
   first caller.
*/

/**
 * How long between one element landing and the next, in seconds.
 *
 * Measured, not chosen. `graphics.ts` was run over the eight references and
 * every gap under eight tenths between one thing arriving and the next was
 * collected — 95 of them. They are bimodal and both modes are clear: 31 at
 * 0.20s and 22 at 0.40s, with almost nothing between 0.20 and 0.35.
 *
 * This was 0.11, which is not either of them and is below the faster one by
 * nearly half. A stagger that tight is the thing that reads as a wobble in a
 * single block rather than as a sequence — which is the sentence the old note
 * here used to warn about, written under a number that was already inside it.
 */
export const STAGGER_S = 0.2;

/**
 * How long a thing takes to arrive, from how much of the frame it covers.
 *
 * The single most useful number the reference study produced, and the one this
 * file had most wrong. Every entrance here took 620ms — 420 for a fade —
 * whatever was arriving. The references do not work that way at all. Median
 * entrance against the area of the box, over 162 arrivals in eight videos:
 *
 *   area 0.20–0.50   n=44   0.20s
 *   area 0.50–0.85   n=49   0.40s
 *   area 0.85–0.95   n=10   0.80s
 *   area 0.95–1.00   n=47   1.10s
 *
 * So a plate takes about a second and a label takes a fifth of one, and a
 * single constant is wrong in *both* directions at once: our small elements
 * dragged at three times the reference speed and our full-frame plates snapped
 * in at half the time one should take. That is what "it doesn't look
 * professional" is, measured — the big things feel cheap because they arrive
 * too fast, and the small things feel sluggish because they arrive too slow.
 *
 * The curve is `BASE * (1 + MASS * area³)`, which follows those four medians to
 * within a sample of the reader's own 20fps grid. Against the same 162
 * arrivals it is wrong by a mean of 376ms where the old constant was wrong by
 * 492ms — and, more to the point, the constant was wrong in a *consistent
 * direction* at each end, which is the part a viewer reads.
 *
 * Cubed rather than linear because that is what the data does: it is nearly
 * flat from 0.2 to 0.5 and then climbs steeply. Area rather than travel
 * because travel explains almost nothing — the medians by travel distance are
 * 0.40, 0.30 and 0.60 seconds, which is not a trend.
 */
export const ENTRANCE_BASE_MS = 200;
export const ENTRANCE_MASS = 4.5;

/** The longest and shortest an arrival may take, whatever the arithmetic says. */
export const ENTRANCE_MIN_MS = 180;
export const ENTRANCE_MAX_MS = 1200;

/**
 * @param area How much of the frame the thing covers, 0..1.
 */
export function entranceMs(area: number): number {
  const bounded = Math.min(1, Math.max(0, area));
  const ms = ENTRANCE_BASE_MS * (1 + ENTRANCE_MASS * bounded ** 3);
  return Math.round(Math.min(ENTRANCE_MAX_MS, Math.max(ENTRANCE_MIN_MS, ms)));
}

/**
 * The gap between arrivals, compressed so the last one still lands in time.
 *
 * A fixed stagger is right for three elements and wrong for twelve: at 0.11 s a
 * twelve-word line is still arriving 1.2 s in, and a two-second title begins
 * fading before its last word has landed — a word nobody ever reads, in a file
 * nobody re-renders.
 *
 * `budgetSeconds` is how long the whole arrival is allowed to take. The ideal
 * gap is used when it fits, and otherwise the gap shrinks until the last
 * element lands exactly at the budget. One element has nothing to stagger
 * against and gets zero, which is what keeps a lone word on the plain path it
 * has always taken.
 */
export function staggerFor(count: number, budgetSeconds: number, ideal: number = STAGGER_S): number {
  if (count < 2) return 0;
  return Math.min(ideal, budgetSeconds / (count - 1));
}

/** The named ways a thing can arrive. Every one of them rides the spring. */
export type Entrance = "rise" | "drop" | "settle" | "fade";

export interface EntranceOptions {
  /** How far it travels to get here, in pixels. Ignored by `settle` and `fade`. */
  travel?: number;
  /** How small it starts. 1 means it does not scale at all. */
  scale?: number;
  /** How long the arrival takes, in milliseconds. */
  ms?: number;
}

export interface EntranceCss {
  /** The transform the element holds before its animation runs. */
  from: string;
  /** Where it ends up, which is always nowhere in particular. */
  to: string;
  ms: number;
}

/**
 * CSS `scale()` the way a stylesheet writes it.
 *
 * `0.86` and `.86` are the same number and not the same string, and this file's
 * output is compared byte for byte by a test that renders the same scene twice.
 * Matching the hand-written form keeps this refactor provably free of pixel
 * changes rather than merely likely to be.
 */
function scaleText(value: number): string {
  const text = String(Number(value.toFixed(4)));
  return text.startsWith("0.") ? text.slice(1) : text;
}

/**
 * An arrival, as the two transforms and the duration it takes between them.
 *
 * `rise` comes up from below and is what a title has always done. `drop` comes
 * down from above, which is the reference's interstitial card and reads as
 * heavier — a thing landing rather than a thing appearing. `settle` scales up
 * in place, for something already where it belongs. `fade` does not move at
 * all, and is the one entrance that does not need the spring: there is no
 * overshoot in an opacity.
 */
export function entranceCss(kind: Entrance, options: EntranceOptions = {}): EntranceCss {
  const travel = options.travel ?? 0;
  const scale = options.scale ?? 1;
  const ms = options.ms ?? (kind === "fade" ? 420 : 620);
  const shrink = scale === 1 ? "" : ` scale(${scaleText(scale)})`;
  const grow = scale === 1 ? "" : " scale(1)";

  if (kind === "fade") return { from: "none", to: "none", ms };
  if (kind === "settle") return { from: `scale(${scaleText(scale)})`, to: "scale(1)", ms };

  const y = kind === "drop" ? -Math.abs(travel) : Math.abs(travel);
  return { from: `translateY(${y}px)${shrink}`, to: `translateY(0)${grow}`, ms };
}

/**
 * A large, soft, low shadow — the one that makes a card look lifted.
 *
 * Two layers rather than one because a single shadow reads as a drop shadow and
 * two read as an object with air under it: a tight one for the contact edge and
 * a wide, faint one for the light falling away. The study calls this out beside
 * the easing and the person-aware placement as one of the three things that
 * separate "professionally designed" from "template", and it is the cheapest of
 * the three by a distance.
 *
 * Scaled against the frame's height for the same reason placement is: a shadow
 * written in fixed pixels is a different shadow at 720p and at 1080p, and the
 * export that people actually post is not always the one anybody looked at.
 */
export function elevation(level: 1 | 2 | 3, frameHeight: number, drift = 0.55): string {
  /*
    Offsets and blurs as fractions of frame height, calibrated against the
    reference rather than doubled until they looked strong.

    The first pass at level 3 used a far blur of 14.9% of frame height. On a
    1920 frame that is a 286px blur offset by 119px under a 307px object, which
    does not read as a shadow at all — it renders as a soft grey slab sitting
    behind the icon, and it was visible in the first frame anybody looked at.
    The reference's cast under a 185px case is about 30px down and 50px of
    blur: 2.3% and 3.9% of its frame height. These are that, with a tighter
    contact layer under it.
  */
  const near = [0.002, 0.004, 0.006][level - 1];
  const far = [0.008, 0.015, 0.024][level - 1];
  const alphaNear = [0.08, 0.1, 0.13][level - 1];
  const alphaFar = [0.1, 0.15, 0.2][level - 1];
  const px = (fraction: number) => Math.max(1, Math.round(frameHeight * fraction));
  /*
    `drift` is how far the shadow falls sideways, as a share of how far it
    falls down — measured off the reference rather than chosen, where the
    shadow under every card leans clearly to the right. A shadow straight
    underneath reads as a UI element; one with a direction reads as an object
    under a light that is somewhere, which is the whole difference this is
    for.
  */
  const sideNear = Math.round(px(near) * drift);
  const sideFar = Math.round(px(far) * drift);
  return (
    `${sideNear}px ${px(near)}px ${px(near * 2.2)}px rgba(0,0,0,${alphaNear}), ` +
    `${sideFar}px ${px(far)}px ${px(far * 1.9)}px rgba(0,0,0,${alphaFar})`
  );
}


/**
 * The pieces a kinetic line arrives in.
 *
 * Whitespace, and nothing cleverer. Splitting on characters would animate
 * Arabic letter by letter, which breaks shaping — the letters are joined, and
 * a joined script pulled apart is a different word. Splitting on punctuation
 * would strand a comma on its own line. A word is what a reader tracks, so a
 * word is the unit.
 */
export function wordsOf(text: string): string[] {
  return text.trim().split(/\s+/).filter((word) => word.length > 0);
}

export interface MotionTitle {
  text: string;
  /** Seconds on the *output* clock. The caller has already remapped it. */
  at: number;
  durationSeconds: number;
  style: "card" | "lower-third" | "word";
  position: "top" | "center" | "bottom";
}

/**
 * A full-frame card that cuts in over the video.
 *
 * The reference study's signature move, and the one it ranked highest for
 * visual effect against effort: between sections the video is replaced for a
 * beat or two by a still, light card carrying an icon and a name. It is what
 * makes a talking head read as a produced explainer rather than a recording.
 *
 * Three details are the whole thing, and all three come from measuring the
 * reference rather than from taste:
 *
 *   - **It cuts.** No dissolve, in or out. The motion belongs to the elements
 *     arriving on the card; a crossfade on top of that reads as a slideshow.
 *   - **The icon lands, it does not appear.** Down from above, fast, with the
 *     spring's overshoot and a large soft shadow under it. That shadow is why
 *     it looks like an object on a surface instead of a picture on a page.
 *   - **Nothing arrives together.** Icon, then name, then note, on a stagger.
 *     Measured at 40–120 ms in the reference; the shared `staggerFor` picks a
 *     gap in that range and compresses it if the card is short.
 *
 * It is drawn in the same transparent overlay every title uses, at full opacity
 * across the whole frame — so a cutaway needs no timeline surgery at all. The
 * video is still there underneath, and simply cannot be seen.
 */
export interface InterstitialCard {
  /** The name on the card — a product, a section, a chapter. */
  name: string;
  /** The line under it, in a pill. Often what the speaker is saying right then. */
  note?: string;
  /**
   * A `file://` or `data:` URL for the icon.
   *
   * Optional, and its absence is a design rather than a gap: a card with no
   * icon draws a rounded tile carrying the name's first letter, which is a
   * real card rather than a hole where one should be. The feature is therefore
   * usable before anything in this product can supply an icon.
   */
  iconUrl?: string;
  /** Seconds on the output clock, like a title's. */
  at: number;
  durationSeconds: number;
}

/**
 * Anything the scene can draw.
 *
 * A union rather than one array per kind, so that adding the device mockup and
 * the person-aware diagram is an entry here and a branch below — not another
 * field on the options, another loop, and another chance for two element types
 * to disagree about what a spring is.
 */
/* ────────────────────────────────────────────────────────────────────────────
   The layer language
   ────────────────────────────────────────────────────────────────────────────

   The interstitial card below is hand-written: its geometry, its colours and
   its three animations are code, measured off one reference. It took most of a
   day and it matches that reference and nothing else. Seven techniques built
   that way is seven days at best, and seven looks that each copy exactly one
   video — which is not what "copy the reference" means.

   Osama's call, and it is the right one: the scene stops being a menu of
   elements and becomes a language. A model that has watched a reference emits
   **layers**, and the renderer draws them. Nothing has to have been
   anticipated.

   ## What a layer is

   A box, something in it, and how it arrives. That is the whole of it, and it
   is enough because it is what the references are actually made of — this was
   checked against six of them before it was written:

     - **r04** — icon interstitials: a fill, a wordmark, an icon, a pill.
     - **r05** — kinetic captions where the keyword is a different colour and
       size inside the same phrase, plus screen recordings inset over video.
     - **r07** — pure motion graphics, no camera at all: colour blocks that
       slide in and split the frame, phone mockups, big type, numbered markers.
     - **r08** — a floating code panel over a talking head, a full-frame brand
       card, and a split with a graphic above a screen recording.

   Every one of those is boxes with content, entrances and shadows. So:

       fill + text + image + text        = the interstitial card
       video box + image box             = a split composition
       image frame + image screen        = a device mockup
       text with styled runs             = a caption with an emphasised word
       fill boxes with slide entrances   = r07's colour blocks
       N image boxes on a stagger        = a grid montage

   ## What it deliberately does not cover

   **Where the person is.** r04 places its diagram in the empty space beside a
   head and never over the face; r05 and r08 keep captions clear of the mouth.
   That needs face detection, which is a capability this renderer does not have
   and which is not a motion problem. Layers take explicit boxes; something
   else will one day compute them.

   **Assets.** A real logo, a 3D product render, r07's mascot. A layer can
   *draw* an image; finding the right image is a different kind of work.

   ## Colours and URLs are validated, never cleaned

   Both go straight into a stylesheet. The card already learned this the hard
   way — stripping quotes from a URL still let a bare `)` close the `url()` and
   start a new declaration. So every caller-supplied value here is matched
   against a strict shape and *refused* if it does not fit, rather than edited
   until it looks safe.
*/

/** Where a layer sits, as fractions of the frame. */
export interface LayerBox {
  x: number;
  y: number;
  w: number;
  h: number;
}

/**
 * A styled piece of a line.
 *
 * This is the thing plain text cannot express and every reference uses:
 * "pretty **Good** at" with the middle word twice the size and green, or
 * "So `here's how`" with half the phrase in a lighter colour. A caption is a
 * sequence of runs, not a string.
 */
export interface TextRun {
  text: string;
  /** Size relative to the layer's own, so 1.8 is nearly twice as large. */
  scale?: number;
  color?: string;
  weight?: number;
  /** A pill behind this run alone. */
  background?: string;
}

/** The devices this can draw. Generic by design — see `LayerContent`. */
export type DeviceKind = "phone" | "browser" | "laptop";

/**
 * How much of a device is frame, and where its screen sits inside it.
 *
 * One table, read by the CSS that draws the body *and* by `deviceScreenBox`,
 * which is what tells ffmpeg where to put the recording. Two copies of these
 * numbers would be a frame and a screen that drift a few pixels apart — a
 * recording with a sliver of bezel showing down one edge, which reads as a
 * rendering fault rather than a design.
 *
 * All fractions of the **layer's own box**, not the frame's.
 */
const DEVICE_GEOMETRY: Record<DeviceKind, { top: number; side: number; bottom: number; radius: number }> = {
  /*
    Measured off r07's phone rather than chosen, which is the correction this
    table needed: the first numbers here were invented, and a bezel at 3.8% of
    the body's width reads as a tablet from 2015. The reference's rim is thin
    and its corner is large — that combination is most of what makes a drawn
    phone read as a current one, and neither is a thing anybody eyeballs
    correctly.
  */
  phone: { top: 0.016, side: 0.026, bottom: 0.016, radius: 0.125 },
  // A title bar with the three dots in it, and a hairline everywhere else.
  browser: { top: 0.085, side: 0.007, bottom: 0.007, radius: 0.03 },
  // A screen with a base under it, which is what tells it from a browser.
  laptop: { top: 0.018, side: 0.014, bottom: 0.085, radius: 0.022 },
};

/**
 * Where a device's screen lands on the frame, as the same four fractions
 * everything else here takes.
 *
 * Exported because the recording that goes inside is placed by ffmpeg, from a
 * plan, and the only way the two can be guaranteed to line up is for both to
 * come from this function.
 */
export function deviceScreenBox(
  device: DeviceKind,
  box: LayerBox,
  frame?: { width: number; height: number },
): { x: number; y: number; w: number; h: number; radius: number } {
  const g = DEVICE_GEOMETRY[device];
  /*
    The side inset is a fraction of the device's *width* and the top and bottom
    are fractions of its *height*, because a bezel is an even thickness in
    pixels and the two axes of the box are not the same length. Reading all
    four off the width — which is what a single number would do — gives a phone
    with a fat forehead and a thin chin on any box that is not square.
  */
  const screen = {
    x: box.x + box.w * g.side,
    y: box.y + box.h * g.top,
    w: box.w * (1 - g.side * 2),
    h: box.h * (1 - g.top - g.bottom),
  };

  /*
    And the corner the content has to be cut to.

    Without this the screen is a rounded hole with a *square* picture behind
    it, and the picture's corners show outside the bezel — four little tabs of
    video sticking out of a phone. It is visible in the first render anybody
    looks at and there was no way for a caller to avoid it, because the inner
    radius is the outer radius minus the bezel and only this file knows either.

    Returned in the units `Layer.radius` takes — a fraction of the *screen
    layer's* shorter side — so a caller writes `radius: screen.radius` and is
    done. That conversion needs the frame's pixel size, because "shorter side"
    is a pixel comparison and the boxes here are fractions of two different
    axes. Without a frame there is no honest answer, so the radius comes back 0
    and a caller that wants round corners has to say what it is rendering to.
  */
  let radius = 0;
  if (frame && frame.width > 0 && frame.height > 0) {
    const deviceShort = Math.min(box.w * frame.width, box.h * frame.height);
    const screenShort = Math.min(screen.w * frame.width, screen.h * frame.height);
    const outer = deviceShort * g.radius;
    const bezel = box.w * g.side * frame.width;
    radius = screenShort > 0 ? Math.max(0, outer - bezel) / screenShort : 0;
  }

  return { ...screen, radius };
}

export type LayerContent =
  | {
      kind: "text";
      runs: TextRun[];
      /** Cap size as a fraction of frame height. */
      size: number;
      color?: string;
      weight?: number;
      align?: "start" | "center" | "end";
      /** Each run arrives after the one before it. */
      staggerRuns?: boolean;
    }
  | { kind: "fill"; color: string }
  /**
   * A gradient, built here from validated parts rather than accepted as CSS.
   *
   * This is the rule the icon URL taught, applied before it costs anything: a
   * caller never hands this file a string that goes into a declaration. It
   * hands two colours and an angle, each of which is checked, and the
   * `linear-gradient(...)` is written here. There is no spelling of `from` or
   * `to` that can end the declaration, because neither is ever anything but a
   * colour.
   *
   * r07 is most of the argument for it existing: its frame is built out of
   * colour blocks and soft washes, and `fill` with one flat colour cannot make
   * any of them.
   */
  | { kind: "gradient"; from: string; to: string; angle?: number }
  | { kind: "image"; url: string; fit?: "contain" | "cover" }
  /**
   * A device to put a screen recording inside.
   *
   * r05 and r08 wrap their recordings in a laptop or a browser window; r07
   * holds up a phone. It is the commonest single move in the references after
   * the caption, and the frame is most of why a recording reads as a product
   * rather than as somebody's desktop.
   *
   * **Drawn, not shipped.** These are CSS — a rounded rect, a bezel, a title
   * bar, three dots — rather than images in the repository, for three reasons
   * and the third is the one that matters:
   *
   *   - they scale to any frame with no second asset and no blurring;
   *   - their colours come from the plan, so a frame can suit the video it is
   *     in rather than being one grey picture;
   *   - and a drawn generic device is a *generic device*. Shipping a picture
   *     of a recognisable phone would be shipping somebody's industrial
   *     design into every customer's video.
   *
   * The screen is left empty on purpose. What goes in it is a clip, and a clip
   * is placed by ffmpeg, not by the browser — `deviceScreenBox` below says
   * exactly where, so the two agree.
   */
  | {
      kind: "device";
      device: DeviceKind;
      /** The body's colour. The screen stays empty whatever this is. */
      shell?: string;
    };

export interface Layer {
  box: LayerBox;
  content: LayerContent;
  /** Seconds on the output clock. */
  at: number;
  durationSeconds: number;
  enter?: Entrance;
  /** How far it travels in, as a fraction of frame height. */
  travel?: number;
  /** How small it starts. */
  from?: number;
  /** Corner radius as a fraction of the layer's shorter side. 0.5 is a circle. */
  radius?: number;
  shadow?: 0 | 1 | 2 | 3;
  /**
   * How soft this layer's own edges are, as a fraction of frame height.
   *
   * Worth being precise about what this can and cannot do: it blurs **this
   * layer**, not what is behind it. The scene is drawn in a browser that has
   * never seen the video — the layer arrives as a transparent picture and
   * ffmpeg composites it — so there is nothing behind it to frost. Asking for
   * `backdrop-filter` here would silently do nothing.
   *
   * What it is for is the soft coloured washes r07 builds its frame out of,
   * glows behind type, and the diffuse shapes that make a flat composition
   * read as lit. Frosted glass over the picture is a real thing and a
   * different mechanism — a blur applied by ffmpeg inside a box — and it is
   * not this.
   */
  blur?: number;
  /** 0..1. Distinct from an entrance: this is where the layer rests. */
  opacity?: number;
  /** Degrees, clockwise. r07 tilts things; nothing else here could. */
  rotate?: number;
  /** Paint order. Higher is nearer the viewer; ties keep the given order. */
  z?: number;
}

/**
 * A colour, or nothing.
 *
 * Hex, `rgb()`/`rgba()`, `hsl()`/`hsla()`, and the handful of bare words worth
 * allowing. Anything else is refused rather than repaired: a colour is a short
 * value with a known shape, so there is no honest reason to accept a string
 * that is not one, and every reason not to — it is written straight into a
 * declaration.
 */
export function safeColor(value: string | undefined): string | null {
  if (!value) return null;
  const v = value.trim();
  if (/^#[0-9a-f]{3,8}$/i.test(v)) return v;
  if (/^(?:rgb|hsl)a?\([\d\s.,%/-]+\)$/i.test(v)) return v;
  if (/^(?:transparent|white|black|currentColor)$/i.test(v)) return v;
  return null;
}

/**
 * An asset URL, matched against a shape rather than cleaned.
 *
 * Two forms, each with its own rule, because they need different ones and a
 * single loose rule that covered both is how this goes wrong:
 *
 *   - **`file:`** — a path the worker wrote itself. Nothing in it that can end
 *     a `url()`, a string, a declaration or a rule.
 *   - **`data:`** — an image the caller embedded. These *must* contain a
 *     semicolon (`;base64,`), which the file rule forbids — the first version
 *     of this function therefore rejected every data URL ever passed to it,
 *     and the check that should have caught that was written with a `|| true`
 *     in it and could not fail. So this one is a whitelist rather than a
 *     blacklist: a known image type, base64, and nothing else in the alphabet.
 *
 * Anything not matching either shape is refused, and a refused asset costs the
 * image rather than the render.
 */
const DATA_IMAGE = /^data:image\/(?:png|jpeg|gif|webp|svg\+xml);base64,[A-Za-z0-9+/]+={0,2}$/i;

export function safeAssetUrl(value: string | undefined): string | null {
  if (!value) return null;
  const v = value.trim();
  if (DATA_IMAGE.test(v)) return v;
  if (!/^file:/i.test(v)) return null;
  if (/["'\\()<>;{}\s]/.test(v)) return null;
  return v;
}

function layerBlock(layer: Layer, index: number, width: number, height: number, curve: string): Block {
  const cls = `l${index}`;
  const box = layer.box;
  const px = (fraction: number, against: number) => Math.round(fraction * against);
  const w = px(box.w, width);
  const h = px(box.h, height);
  const shortSide = Math.max(1, Math.min(w, h));

  /*
    How long it takes to arrive is a property of how big it is.

    A layer knows its own box, so this is the one place in the file where the
    area is exact rather than inferred from a style name — which is why the
    curve lives here and the title renderer passes its own estimate.
  */
  const plain = entranceCss(layer.enter ?? "fade", {
    travel: Math.round((layer.travel ?? 0.045) * height),
    scale: layer.from ?? 1,
    ms: entranceMs(box.w * box.h),
  });
  /*
    A tilt is part of where the layer rests, so it has to be in **both** ends
    of the entrance.

    Written as a resting `transform` on its own, the animation's `to` would be
    a transform without it and the layer would quietly un-tilt as it landed —
    a rotation that exists in the CSS, is visible in a still, and disappears in
    motion. Worse than not having it.
  */
  const spinPart = (t: string) => {
    const s = Number.isFinite(layer.rotate) && Math.round(layer.rotate!) % 360 !== 0
      ? ` rotate(${Math.round(layer.rotate!) % 360}deg)`
      : "";
    if (!s) return t;
    return t === "none" ? s.trim() : `${t}${s}`;
  };
  const enter = { from: spinPart(plain.from), to: spinPart(plain.to), ms: plain.ms };
  const end = (layer.at + layer.durationSeconds).toFixed(3);
  const radius = layer.radius ? Math.round(shortSide * layer.radius) : 0;
  const shadow = layer.shadow ? elevation(layer.shadow, height) : "none";
  /*
    Blur is measured against frame height for the reason everything else here
    is: the same layer on a 720 and a 1920 frame has to look like the same
    layer, and a blur in fixed pixels is two different softnesses.
  */
  const blur = layer.blur && layer.blur > 0 ? Math.max(1, Math.round(layer.blur * height)) : 0;
  const rest = layer.opacity === undefined ? 1 : Math.min(1, Math.max(0, layer.opacity));
  const spin = Number.isFinite(layer.rotate) ? Math.round(layer.rotate!) % 360 : 0;

  let inner = "";
  let extra = "";
  let background = "transparent";

  if (layer.content.kind === "fill") {
    background = safeColor(layer.content.color) ?? "transparent";
  } else if (layer.content.kind === "gradient") {
    /*
      Built, not passed through.

      Both stops go through `safeColor` and the angle is clamped to a number,
      so what reaches the stylesheet is assembled here out of three values that
      have each been checked. A caller cannot supply a gradient string at all,
      which is the point: there is no spelling of one that can end the
      declaration it sits in.

      One refused stop loses the whole gradient rather than half of it — a
      layer that silently became a flat colour is worse than one that is
      plainly absent.
    */
    const from = safeColor(layer.content.from);
    const to = safeColor(layer.content.to);
    const angle = Number.isFinite(layer.content.angle) ? Math.round(layer.content.angle!) % 360 : 180;
    background = from && to ? `linear-gradient(${angle}deg, ${from}, ${to})` : "transparent";
  } else if (layer.content.kind === "device") {
    /*
      The body, drawn; the screen, left alone.

      Everything here is one nested div rather than borders on the outer box,
      because the outer box already carries the layer's radius, shadow, blur
      and rotation — and a device that picked up the layer's own corner radius
      on top of its bezel would be a rounded rectangle inside a rounded
      rectangle with two different curves.

      The screen is transparent, not black. Whatever ffmpeg put in that
      rectangle is underneath, and painting it would be painting over the
      recording this frame exists to hold.
    */
    const kind = layer.content.device;
    const g = DEVICE_GEOMETRY[kind];
    const shell = safeColor(layer.content.shell) ?? "#1b1f27";
    const side = Math.round(w * g.side);
    const top = Math.round(h * g.top);
    const bottom = Math.round(h * g.bottom);
    const outerRadius = Math.round(shortSide * g.radius);
    const dot = Math.max(2, Math.round(top * 0.26));

    /*
      The body is a border, so the screen is a hole.

      The first spelling of this drew an opaque body and laid a transparent
      "screen" div over it — which is not a hole, it is a window onto the body
      behind it, and it rendered three black slabs with nothing showing
      through. What goes in the screen is a clip placed by ffmpeg *underneath*
      this layer, so the middle has to be genuinely empty.

      A border-only box gives that for free, and gives something else worth
      having: with `border-radius` and a border, the browser computes the inner
      corner as the outer radius minus the border width, which is what a real
      bezel does. A separately specified inner radius was one more number to
      keep in step with the geometry, and it is gone.
    */
    /*
      And a sheen on the glass.

      This is the last tell, and it is the one that survives being looked at:
      a screen with no reflection is a picture of a screen. The reference's
      phone carries a soft diagonal highlight across the top third of the
      glass, brighter at the corner the light comes from and gone by the
      middle.

      It is drawn by the *device* rather than by whatever is inside the screen,
      which is the only place it can be: the content is a clip ffmpeg placed
      underneath, and glass is in front of what it covers. So the device layer
      sits above the content and paints this over it.

      Not on a browser window. A browser is a rectangle on a screen, not a
      screen — a reflection on it would be a reflection on nothing.
    */
    const glass = kind === "browser" ? "" : `<div class="glass"></div>`;
    inner = `<div class="dev"></div>${glass}${
      kind === "browser"
        ? `<div class="dots"><i></i><i></i><i></i></div>`
        : kind === "phone"
          ? `<div class="notch"></div>`
          : ""
    }`;

    /*
      Two rims, and no gradient on the bezel — which is a decision, not a gap.

      A flat border of one colour reads as paper; a real rim catches light at
      its outer and inner edges, and that highlight is the clearest single tell
      between a drawn mockup and a photographed one.

      A gradient *along* the bezel would be better still, and the obvious way
      to get it — a `linear-gradient` background with a transparent border —
      does not work here: the background fills the padding box as well, so the
      screen stops being a hole and the whole point of this element is lost.
      It was tried and the pixel check caught it immediately. `border-image`
      paints only the border and would be exactly right, except that it
      disables `border-radius`, and a square-cornered phone is a worse lie than
      a flat one.

      So: a solid bezel with a light line just outside it and another just
      inside. That is most of the effect and none of the risk.
    */
    const rim = Math.max(1, Math.round(shortSide * 0.004));
    extra = `
      .${cls} .dev {
        position:absolute; inset:0; box-sizing:border-box;
        background:transparent;
        border-style:solid; border-color:${shell};
        border-width:${top}px ${side}px ${bottom}px ${side}px;
        border-radius:${outerRadius}px;
        box-shadow:
          0 0 0 ${rim}px rgba(255,255,255,.14),
          inset 0 0 0 ${rim}px rgba(255,255,255,.1);
      }
      .${cls} .glass {
        position:absolute;
        left:${side}px; top:${top}px; right:${side}px; bottom:${bottom}px;
        border-radius:${Math.max(0, outerRadius - side)}px;
        background:linear-gradient(118deg,
          rgba(255,255,255,.16) 0%,
          rgba(255,255,255,.06) 22%,
          rgba(255,255,255,0) 46%);
        pointer-events:none;
      }
      .${cls} .dots {
        position:absolute; top:${Math.round(top / 2 - dot / 2)}px; left:${Math.round(side + dot)}px;
        display:flex; gap:${Math.round(dot * 0.8)}px;
      }
      .${cls} .dots i {
        width:${dot}px; height:${dot}px; border-radius:50%;
        background:rgba(255,255,255,.3); display:block;
      }
      /*
        The notch is on the screen, not on the bezel.

        Drawn on the rim it is a scratch in the metal; drawn on the glass just
        below the top edge, dark and wide, it is what every phone made since
        2020 actually looks like. The reference's is a pill roughly a third of
        the body's width, measured rather than guessed: a narrow one reads as a
        speaker grille and a wide one as a browser tab.
      */
      .${cls} .notch {
        position:absolute; top:${Math.round(top + h * 0.012)}px; left:50%;
        transform:translateX(-50%);
        width:${Math.round(w * 0.32)}px; height:${Math.max(4, Math.round(h * 0.022))}px;
        border-radius:999px; background:#0b0d11;
      }`;
    background = "transparent";
  } else if (layer.content.kind === "image") {
    const url = safeAssetUrl(layer.content.url);
    const fit = layer.content.fit === "cover" ? "cover" : "contain";
    /*
      A refused URL leaves an empty box rather than an error.

      The same choice the card makes, for the same reason: a layer that cannot
      find its image should cost the image, not the render. Something visibly
      missing in a frame is a bug somebody reports; a render that failed is a
      customer who lost their afternoon.
    */
    background = url ? `center/${fit} no-repeat url("${url}")` : "transparent";
  } else {
    const text = layer.content;
    const size = Math.round(text.size * height);
    const align = text.align === "start" ? "flex-start" : text.align === "end" ? "flex-end" : "center";
    const color = safeColor(text.color) ?? "#fff";
    const weight = Math.min(900, Math.max(100, Math.round(text.weight ?? 800)));

    /*
      Runs, and the stagger between them.

      `inline-block` per run for the same reason the kinetic title uses it: an
      atomic inline is neutral to the bidi algorithm, so a run of them lays out
      in the paragraph's own direction and Arabic starts on the right with no
      direction logic here.
    */
    const gap = text.staggerRuns ? staggerFor(text.runs.length, layer.durationSeconds * 0.5) : 0;
    inner = text.runs
      .map((run, i) => {
        const runColor = safeColor(run.color);
        const runBackground = safeColor(run.background);
        const style = [
          run.scale && run.scale !== 1 ? `font-size:${(run.scale * 100).toFixed(1)}%` : "",
          runColor ? `color:${runColor}` : "",
          run.weight ? `font-weight:${Math.min(900, Math.max(100, Math.round(run.weight)))}` : "",
          runBackground
            ? `background:${runBackground};padding:.08em .3em;border-radius:.22em`
            : "",
          gap ? `animation-delay:${(layer.at + i * gap).toFixed(3)}s` : "",
        ]
          .filter(Boolean)
          .join(";");
        return `<i${style ? ` style="${style}"` : ""}>${escape(run.text)}</i>`;
      })
      .join(" ");

    extra = `
      .${cls} .t {
        font:${weight} ${size}px/1.08 Inter, "DejaVu Sans", system-ui, sans-serif;
        color:${color}; letter-spacing:-0.025em; text-align:center;
        display:flex; flex-wrap:wrap; gap:0 .28em;
        align-items:center; justify-content:${align};
        width:100%;
      }
      .${cls} i { font-style:normal; display:inline-block; }`;
    if (gap) {
      extra += `
      .${cls} i { opacity:0; transform:${enter.from}; animation: runin ${enter.ms}ms ${curve} forwards; }`;
    }
  }

  /*
    When runs arrive one at a time, the layer itself must already be there —
    otherwise the layer's own entrance and each run's entrance both run, and
    the text arrives twice.
  */
  const runsCarryTheEntrance = layer.content.kind === "text" && Boolean(layer.content.staggerRuns);

  return {
    css: `
      .${cls} {
        position:absolute;
        left:${px(box.x, width)}px; top:${px(box.y, height)}px;
        width:${w}px; height:${h}px;
        display:flex; align-items:center; justify-content:center;
        background:${background};
        ${radius ? `border-radius:${radius}px;` : ""}
        ${shadow === "none" ? "" : `box-shadow:${shadow};`}
        ${blur ? `filter:blur(${blur}px);` : ""}
        ${layer.z === undefined ? "" : `z-index:${Math.round(layer.z)};`}
        overflow:hidden;
        opacity:${runsCarryTheEntrance ? rest : 0};
        ${runsCarryTheEntrance ? (spin ? `transform:${spinPart("none")};` : "") : `transform:${enter.from};`}
        animation: ${
          runsCarryTheEntrance
            ? ""
            : `in-${cls} ${enter.ms}ms ${curve} ${layer.at.toFixed(3)}s forwards, `
        }out-${cls} 1ms linear ${end}s forwards;
      }
      @keyframes in-${cls} { to { opacity:${rest}; transform:${enter.to} } }
      @keyframes out-${cls} { to { opacity:0 } }${extra}`,
    /*
      Text is wrapped in its own flex row; a device is already a stack of
      absolutely-placed pieces and wrapping it would give it a second box to
      be positioned inside. Everything else draws with CSS alone.
    */
    html: `<div class="${cls}">${
      layer.content.kind === "text"
        ? `<div class="t" dir="auto">${inner}</div>`
        : layer.content.kind === "device"
          ? inner
          : ""
    }</div>`,
  };
}

export type SceneElement =
  | ({ kind: "title" } & MotionTitle)
  | ({ kind: "card" } & InterstitialCard)
  | ({ kind: "layer" } & Layer);

export interface MotionSceneOptions {
  width: number;
  height: number;
  fps: number;
  /**
   * Titles, kept as their own field because every existing caller passes them
   * and a rename would be churn in a 7,000-line renderer for no gain. They are
   * folded into `elements` below, in order, before anything is drawn.
   */
  titles: MotionTitle[];
  /** Everything else the scene draws. */
  elements?: SceneElement[];
  /** Total length of the layer, in seconds. */
  durationSeconds: number;
}

/**
 * Where a title sits, measured against the height it is inset from.
 *
 * Percentage padding in CSS resolves against the containing block's *inline*
 * size — the width — never the height. So these were a constant fraction of
 * the width and a wildly varying fraction of the height: measured, the same
 * "bottom" title sat 12.3% up a 9:16 frame and 33.9% up a 16:9 one. A title
 * placed by the same plan landed in visibly different places depending on the
 * shape it was exported to, which is the failure the image overlay's own
 * comment says it avoids.
 *
 * `vh` is the frame's height, which is what "12% from the top" was always
 * meant to mean.
 */
const PLACEMENT: Record<MotionTitle["position"], string> = {
  top: "align-items:flex-start;padding-top:12vh",
  center: "align-items:center",
  bottom: "align-items:flex-end;padding-bottom:18vh",
};

/**
 * The scene, as a self-contained page.
 *
 * Written as one document with one animation per title rather than a timeline
 * abstraction: the browser already has a timeline, and every layer of
 * indirection over it is a layer that can disagree with what is drawn.
 *
 * The one landing keyframe below — `word-in` — stays spelled out rather than
 * built from `entranceCss`, because it is shared by every kinetic title on the
 * page and so cannot carry any single title's numbers. Each word that uses it
 * still *starts* from a transform `entranceCss` wrote.
 *
 * Nothing in here may contain a backtick. The whole page is one template
 * literal, so a backtick in a CSS comment ends the string and the file stops
 * compiling — which is how this note came to be up here rather than down
 * beside the rule it describes.
 */
/** A drawn element, as the two things a page is made of. */
interface Block {
  css: string;
  html: string;
}

/**
 * User text, on its way into markup.
 *
 * Hoisted out of the title builder because the card carries a name and a note
 * that came from the same place — a person typing — and an escape that lives
 * inside one element kind is an escape the next element kind forgets.
 */
function escape(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function titleBlock(title: MotionTitle, index: number, height: number, curve: string): Block {
  const cls = `t${index}`;
  const size = title.style === "card" ? 0.11 : title.style === "lower-third" ? 0.062 : 0.135;
  const weight = title.style === "word" ? 900 : 800;
  // Escaped rather than trusted: a title is user text, and a page is a
  // place where user text becomes markup if nobody stops it.
  const safe = escape(title.text);
  const rise = Math.round(height * 0.05);

  /**
   * The kinetic style, which until this round was not kinetic.
   *
   * `word` is documented — in the schema, and in the instructions the model
   * reads — as words arriving on the screen. It rendered the whole string
   * as one block with the same curve as a card, so a three-word line
   * landed as a slab. Nothing failed: the frames had ink on them, the
   * export played, and the only thing wrong was that the feature named
   * after words did not treat them as words. That is this codebase's
   * oldest enemy, and it had been sitting inside the one operation whose
   * entire purpose is to be *seen*.
   *
   * Each word is an inline-block, which matters for more than the
   * transform it needs: an atomic inline is neutral to the bidi algorithm,
   * so a run of them is laid out in the paragraph's own direction. The
   * first word of an Arabic line therefore lands on the **right**, and the
   * first word of an English line on the left, with no direction logic
   * here at all — the same reason `dir="auto"` is on the span rather than a
   * rule we wrote ourselves.
   */
  const pieces = title.style === "word" ? wordsOf(title.text) : [];
  const kinetic = pieces.length > 1;
  /*
    A word arrives from a little lower and a little smaller than a card
    does. Both are the same `rise`, on the same spring, for the same 620ms
    — the two numbers below are the only thing that ever differed, and now
    they are the only thing written down.
  */
  const arrival = entranceCss("rise", { travel: rise, scale: kinetic ? 0.86 : 0.94 });
  /**
   * Every word must be on screen while the title still is — half the
   * title's life is the budget the arrival has to fit inside.
   *
   * The rule itself now lives in `staggerFor`, because the interstitial
   * card has the same problem with its icon, its wordmark and its pill.
   */
  const stagger = kinetic ? staggerFor(pieces.length, title.durationSeconds * 0.5) : 0;

  const shared = `
    .${cls} {
      position:absolute; inset:0; display:flex; justify-content:center;
      ${PLACEMENT[title.position]};
    }
    .${cls} span {
      font: ${weight} ${Math.round(height * size)}px/1.1 Inter, "DejaVu Sans", system-ui, sans-serif;
      color:#fff; text-align:center; max-width:82%;
      letter-spacing:-0.02em;
      text-shadow: 0 ${Math.round(height * 0.004)}px ${Math.round(height * 0.012)}px rgba(0,0,0,.55);
    }
    @keyframes out-${cls} { to { opacity:0 } }`;

  if (kinetic) {
    return {
      css: `${shared}
    .${cls} {
      opacity:1;
      animation: out-${cls} 320ms ease-in ${(title.at + title.durationSeconds).toFixed(3)}s forwards;
    }
    .${cls} i {
      font-style:normal; display:inline-block; opacity:0;
      transform: ${arrival.from};
      animation: word-in ${arrival.ms}ms ${curve} forwards;
    }`,
      html: `<div class="${cls}"><span dir="auto">${pieces
        .map(
          (word, w) =>
            `<i style="animation-delay:${(title.at + w * stagger).toFixed(3)}s">${escape(word)}</i>`,
        )
        .join(" ")}</span></div>`,
    };
  }

  return {
    css: `${shared}
    .${cls} {
      opacity:0;
      animation: in-${cls} ${arrival.ms}ms ${curve} ${title.at}s forwards,
                 out-${cls} 320ms ease-in ${(title.at + title.durationSeconds).toFixed(3)}s forwards;
    }
    .${cls} span {
      transform: ${arrival.from};
      animation: rise-${cls} ${arrival.ms}ms ${curve} ${title.at}s forwards;
    }
    @keyframes in-${cls} { to { opacity:1 } }
    @keyframes rise-${cls} { to { transform: ${arrival.to} } }`,
    // `dir="auto"` for the same reason the editor carries it, and with more
    // at stake: a title is *burned into the file*. The browser reads the
    // first strong character and lays the line out that way, so an Arabic
    // title's question mark ends the sentence instead of opening it, and an
    // English title is laid out exactly as it was before. Measured, not
    // assumed: without it the bang in «٥ أسرار للنجاح!» sits four fifths of
    // the way across the line — at the wrong end, permanently.
    html: `<div class="${cls}"><span dir="auto">${safe}</span></div>`,
  };
}

/**
 * The interstitial card.
 *
 * Everything about how it moves comes out of the shared vocabulary above, and
 * that is the point of this element existing in this patch rather than a later
 * one: it is the proof that the vocabulary is a vocabulary. The icon uses
 * `drop`; the name and the note use `fade`; the gaps between the three come
 * from `staggerFor`; the shadow comes from `elevation`. Not one curve, delay or
 * shadow is written here.
 *
 * ## Every number below was measured, not chosen
 *
 * The first version of this was built from a written description of the
 * reference and it was wrong in five ways at once — name under the icon rather
 * than behind it, pill tucked against the icon rather than sitting low, pill
 * colours inverted, shadow falling straight down, group centred rather than
 * high. It looked fine. It looked like a different product.
 *
 * So these come off the frames instead:
 *
 *   - **Ground `#ECECEC`** — sampled at RGB(236,236,236), corner and centre.
 *   - **The group sits high.** Ink runs 31.6%–64.0% of frame height, so the
 *     card's mass is above the middle and the lower third is deliberately
 *     empty. Centring it is the single change that makes this read as a
 *     template.
 *   - **The name is behind the icon.** Not above it with a gap — the tile
 *     overlaps the wordmark's lower edge, which is why the card reads as two
 *     layered objects instead of a stacked list.
 *   - **The pill is far down**, centred at 69.6% of height and 33% of width,
 *     filled RGB(164,164,164) with white text. It is a caption on the card,
 *     not a subtitle under the name.
 *   - **The tile is a white case** holding the icon with padding, the way an
 *     app icon sits on a light card, rather than the icon alone.
 *
 * ## And the one thing that is not a number
 *
 * **It cuts.** 1 ms animations at each end. The layer is sampled every
 * 1/(fps x 4) of a second — 8 ms at 30fps — so a 1 ms ramp can never be caught
 * halfway by a frame that gets written: the card is absent, then wholly
 * present, then absent. A dissolve here is the easiest possible way to make
 * this look like a slideshow, and the reference never does it.
 */
function cardBlock(
  card: InterstitialCard,
  index: number,
  width: number,
  height: number,
  curve: string,
): Block {
  const cls = `c${index}`;
  const short = Math.min(width, height);

  /*
    Three arrivals, and the gap between them.

    Half the card's life is the budget, the same share a kinetic line gives its
    words — so a card held for 2 s staggers at the ideal 110 ms and a card held
    for half a second compresses rather than showing a note after it is gone.
  */
  const pieces = 1 + (card.name ? 1 : 0) + (card.note ? 1 : 0);
  const gap = staggerFor(pieces, card.durationSeconds * 0.5);

  const drop = entranceCss("drop", { travel: Math.round(height * 0.045), scale: 0.86, ms: 520 });
  const soften = entranceCss("fade", { ms: 380 });

  /*
    The wordmark, sized to fit rather than sized and hoped.

    At a fixed share of the frame, "Higgsfield" ran off both edges of a 1080
    frame while "Apify" sat comfortably inside it — the reference's names are
    all short, so a single number looked right until the first long one.

    There is no way to measure text in a string builder, so this estimates:
    a heavy grotesque at this tracking advances about 0.56 of its own size per
    character, and the line is allowed 86% of the frame. The estimate is
    generous rather than exact — it errs small, because a wordmark a little
    under its ideal size is invisible and one a little over is cut in half.

    `MAX_NAME_SHARE` is the reference's own proportion, measured: "Granola" is
    120px of cap on a 720-wide frame. A short name gets that and no more; a
    long one gets whatever fits.

    An estimate is only safe if something checks it, so `motion-test` renders a
    deliberately long name and asserts no ink reaches the frame edge.
  */
  const MAX_NAME_SHARE = 0.17;
  const ADVANCE_PER_CHAR = 0.56;
  const glyphs = Math.max(1, [...card.name.trim()].length);
  const nameSize = Math.round(
    Math.min(short * MAX_NAME_SHARE, (width * 0.86) / (glyphs * ADVANCE_PER_CHAR)),
  );

  /*
    Measured off the Granola card, which is the one with a colour distinct
    enough to find without guessing:

      coloured icon   x 276-443  =  23.2% of frame width, square
      its centre      y          =  49.7% of frame height
      pill            x 240-479  =  33.2% of width, centred at 65.5%

    The white case is that icon plus a thin border — the reference fills 90% of
    the case with the logo, so the white reads as an edge rather than as a card
    the logo is sitting on. The first build had it at 82% with a large radius,
    which is why it read as a big white tile with something small inside it.

    `NAME_BASELINE` is the overlap, and the overlap is the whole look: the case
    covers the bottom quarter of the letters, so the two read as layered
    objects. A wordmark resting neatly above the icon is a list.
  */
  const ICON_SHARE = 0.232;
  const ICON_FILLS_CASE = 0.9;
  const CASE_CENTRE = 0.497;
  const NAME_BASELINE = 0.46;

  const caseSize = Math.round((short * ICON_SHARE) / ICON_FILLS_CASE);
  const caseRadius = Math.round(caseSize * 0.235);
  const pad = Math.round((caseSize * (1 - ICON_FILLS_CASE)) / 2);
  const end = (card.at + card.durationSeconds).toFixed(3);

  /*
    An icon, or the letter that stands in for one.

    The fallback is a real card rather than a gap: the same case, the same
    shadow, the same landing, carrying the name's first character. It means
    this operation is useful today, before anything in this product knows how
    to find a product's logo — and when that arrives, it changes what is inside
    the case and nothing else.

    The URL goes into a CSS `url()`, and it is the only field on this card that
    is not plain text. It is *validated* rather than cleaned, because cleaning
    it is what failed: stripping quotes and backslashes still let

        a") ; background:url("http://evil/x

    through as

        url(a) ; background:url(http://evil/x)

    — the caller's own bare `)` closed the url() early and everything after the
    semicolon became a second declaration inside our stylesheet. A test written
    for exactly this caught it; nothing else would have.

    So: a `file:` or `data:` URL, carrying none of the characters that can end a
    url(), a string, a declaration or a rule. Anything else is not cleaned into
    something safe, it is simply refused — and a refused icon falls back to the
    letter, which is a card rather than a hole. Losing an icon is a cost worth
    paying to make this unable to inject.
  */
  const proposed = card.iconUrl?.trim() ?? "";
  const usable = /^(?:file:|data:)/i.test(proposed) && !/["'\\()<>;{}\s]/.test(proposed);
  const safeUrl = usable ? proposed : "";
  const letter = escape([...card.name.trim()][0] ?? "");

  /*
    A colour for the card that has no logo.

    The reference's cards live off their icons — Granola's green, Composio's
    cyan, Notion's black-on-white. A grey letter on a white tile has the right
    geometry and none of the life, which is exactly how the first build of this
    looked next to the real thing.

    So the placeholder takes a hue from the name itself: same name, same colour,
    every render, without a table of brands to maintain or a network call to
    make. It is honestly a placeholder — it is not pretending to be anybody's
    logo — but it is a *coloured object*, which is what the composition needs
    to read correctly. When real logos arrive they replace the inside of the
    case and nothing else moves.

    Saturation and lightness are fixed so no name can draw a colour that fights
    the near-white ground or vanishes into it.
  */
  let hash = 0;
  for (const ch of card.name) hash = (hash * 31 + ch.codePointAt(0)!) % 360;
  const tint = `hsl(${hash} 62% 58%)`;

  return {
    css: `
      .${cls} {
        position:absolute; inset:0; opacity:0;
        background:#ECECEC;
        animation: on-${cls} 1ms linear ${card.at}s forwards,
                   off-${cls} 1ms linear ${end}s forwards;
      }
      @keyframes on-${cls} { to { opacity:1 } }
      @keyframes off-${cls} { to { opacity:0 } }
      .${cls} .v {
        position:absolute; inset:0;
        background: radial-gradient(120% 85% at 50% 42%, rgba(0,0,0,0) 55%, rgba(0,0,0,.06) 100%);
      }
      .${cls} .n {
        position:absolute; left:0; right:0;
        top:${Math.round(height * NAME_BASELINE - nameSize)}px;
        font:800 ${nameSize}px/1 Inter, "DejaVu Sans", system-ui, sans-serif;
        color:#111; letter-spacing:-0.035em; text-align:center;
        white-space:nowrap;
        text-shadow:0 ${Math.round(height * 0.006)}px ${Math.round(height * 0.018)}px rgba(0,0,0,.16);
        opacity:0;
        animation: nin-${cls} ${soften.ms}ms ease-out ${(card.at + gap).toFixed(3)}s forwards;
      }
      @keyframes nin-${cls} { to { opacity:1 } }
      .${cls} .i {
        position:absolute; left:50%; top:${(CASE_CENTRE * 100).toFixed(1)}%;
        width:${caseSize}px; height:${caseSize}px; margin:${-caseSize / 2}px 0 0 ${-caseSize / 2}px;
        border-radius:${caseRadius}px; background:#fff; padding:${pad}px;
        box-sizing:border-box; box-shadow:${elevation(3, height)};
        opacity:0; transform:${drop.from};
        animation: iin-${cls} ${drop.ms}ms ${curve} ${card.at.toFixed(3)}s forwards;
      }
      @keyframes iin-${cls} { to { opacity:1; transform:${drop.to} } }
      .${cls} .g {
        width:100%; height:100%; border-radius:${Math.round(caseRadius * 0.78)}px;
        background:${safeUrl ? `#F2F2F2 url("${safeUrl}") center/contain no-repeat` : tint};
        display:flex; align-items:center; justify-content:center;
        font:800 ${Math.round(caseSize * 0.5)}px/1 Inter, "DejaVu Sans", system-ui, sans-serif;
        color:#fff;
      }
      .${cls} .p {
        position:absolute; left:50%; top:65.5%; transform:translate(-50%,-50%);
        font:700 ${Math.round(short * 0.038)}px/1 Inter, "DejaVu Sans", system-ui, sans-serif;
        color:#fff; background:#A4A4A4; text-align:center; max-width:78%;
        white-space:nowrap; overflow:hidden; text-overflow:ellipsis;
        padding:${Math.round(short * 0.018)}px ${Math.round(short * 0.034)}px;
        border-radius:${Math.round(short * 0.02)}px;
        opacity:0;
        animation: pin-${cls} ${soften.ms}ms ease-out ${(card.at + gap * 2).toFixed(3)}s forwards;
      }
      @keyframes pin-${cls} { to { opacity:1 } }`,
    /*
      The name before the case in source order, so the case paints over it.

      This is the overlap, and it is the whole look: the wordmark is a layer
      *behind* the icon rather than a line above it. Reversing these two lines
      turns a designed card into a stacked list, and nothing about the CSS
      would look wrong.

      `dir="auto"` on both pieces of language, for the reason a title carries
      it: the browser reads the first strong character, which is a better rule
      than one written here, and a card is burned into the file.
    */
    html:
      `<div class="${cls}"><div class="v"></div>` +
      `<div class="n" dir="auto">${escape(card.name)}</div>` +
      `<div class="i"><div class="g">${safeUrl ? "" : letter}</div></div>` +
      (card.note ? `<div class="p" dir="auto">${escape(card.note)}</div>` : "") +
      `</div>`,
  };
}

export function sceneHtml(options: MotionSceneOptions): string {
  const { width, height } = options;
  const curve = spring();

  /*
    One list, in the order the caller gave it.

    Titles arrive in their own field and are folded in first, so the class
    names they get — and therefore the stacking order on the page — are exactly
    what they were before there was anything else to draw.
  */
  const elements: SceneElement[] = [
    ...options.titles.map((title) => ({ kind: "title" as const, ...title })),
    ...(options.elements ?? []),
  ];

  const blocks = elements.map((element, index) => {
    if (element.kind === "card") return cardBlock(element, index, width, height, curve);
    if (element.kind === "layer") return layerBlock(element, index, width, height, curve);
    return titleBlock(element, index, height, curve);
  });

  return `<!doctype html><html><head><meta charset="utf-8"><style>
  html,body { margin:0; padding:0; width:${width}px; height:${height}px; background:transparent; overflow:hidden }
  @keyframes word-in { to { opacity:1; transform: translateY(0) scale(1) } }
  @keyframes runin { to { opacity:1; transform: none } }
  ${blocks.map((b) => b.css).join("\n")}
  </style></head><body>${blocks.map((b) => b.html).join("")}</body></html>`;
}

export interface MotionLayer {
  /** ffmpeg input pattern for the frame sequence, e.g. `/tmp/x/m%06d.png`. */
  pattern: string;
  frames: number;
  fps: number;
}

/**
 * Render the scene to a transparent PNG sequence.
 *
 * Returns `null` when no browser is available, which is a real case — the
 * worker image carries one, a laptop running the suite may not — and a missing
 * browser must cost the titles, not the render.
 */
/**
 * The parts of Playwright and of the page we actually touch.
 *
 * Written out rather than imported for the reason above, and kept deliberately
 * narrow: this is the contract this file depends on, and a change to any of it
 * should be a compile error rather than a black screen in an export.
 */
interface ChromiumLike {
  launch(options: { executablePath?: string; args: string[] }): Promise<BrowserLike>;
}
interface BrowserLike {
  newPage(options: {
    viewport: { width: number; height: number };
    deviceScaleFactor: number;
  }): Promise<PageLike>;
  close(): Promise<void>;
}
interface PageLike {
  goto(url: string, options: { waitUntil: "load" }): Promise<unknown>;
  evaluate<A>(fn: (arg: A) => unknown, arg?: A): Promise<unknown>;
  screenshot(options: { path: string; omitBackground: boolean }): Promise<unknown>;
  close(): Promise<void>;
}

/**
 * `document` inside a page.evaluate callback is Chromium's, not Node's. Only
 * the two members these callbacks use are declared, which is also the shortest
 * possible statement of what the animation capture depends on.
 */
declare const document: {
  fonts: { ready: Promise<unknown> };
  getAnimations(): Array<{ pause(): void; currentTime: number | null }>;
};

export async function renderMotionLayer(
  options: MotionSceneOptions,
  outDir: string,
): Promise<MotionLayer | null> {
  // playwright-core is deliberately not a dependency of this package: it is
  // installed into the runtime image (see the Dockerfile) and marked external
  // in the bundle, because a laptop running the test suite should not have to
  // download a browser driver to typecheck a video encoder. That means there
  // are no types for it here, and the specifier is held in a variable so the
  // compiler does not try to resolve one.
  // Two names for the same driver. The runtime image installs `playwright-core`
  // because it is the smaller of the two and downloads no browsers; a machine
  // that has run the test suite usually has the full `playwright` instead. Both
  // export the same `chromium`, so trying them in order is the difference
  // between titles that render everywhere and titles that render in production
  // only — where nobody can see them fail.
  let chromium: ChromiumLike | null = null;
  for (const specifier of ["playwright-core", "playwright"]) {
    try {
      const mod = (await import(specifier)) as { chromium?: ChromiumLike };
      if (mod.chromium) {
        chromium = mod.chromium;
        break;
      }
    } catch {
      // Not installed under that name. Try the other.
    }
  }
  if (!chromium) return null;

  /**
   * Where the browser is — or, usually, not saying.
   *
   * The runtime image installs Chromium from the distribution and points
   * CHROMIUM_PATH at it, because playwright-core ships no browser of its own.
   * Everywhere else — a CI runner after `playwright install`, a laptop —
   * Playwright already knows where its own build lives, and naming a path it
   * does not have is how the whole feature silently turns itself off. So the
   * path is passed only when it was actually configured.
   */
  const executablePath = process.env["CHROMIUM_PATH"]?.trim();
  let browser;
  try {
    browser = await chromium.launch({
      ...(executablePath ? { executablePath } : {}),
      args: ["--no-sandbox", "--force-color-profile=srgb", "--disable-lcd-text"],
    });
  } catch {
    return null;
  }

  try {
    await mkdir(outDir, { recursive: true });
    const html = path.join(outDir, "scene.html");
    await writeFile(html, sceneHtml(options), "utf8");

    const page = await browser.newPage({
      viewport: { width: options.width, height: options.height },
      deviceScaleFactor: 1,
    });
    await page.goto(`file://${html}`, { waitUntil: "load" });
    // Fonts must resolve before the first frame or frame 0 renders in a
    // fallback face and every later frame renders in the real one — a seam
    // nobody would guess at from the code.
    await page.evaluate(() => document.fonts.ready);

    const sampleRate = options.fps * MOTION_SUBSAMPLES;
    const total = Math.ceil(options.durationSeconds * sampleRate);
    for (let i = 0; i < total; i += 1) {
      const timeMs = (i / sampleRate) * 1000;
      await page.evaluate((t) => {
        for (const animation of document.getAnimations()) {
          animation.pause();
          animation.currentTime = t;
        }
      }, timeMs);
      await page.screenshot({
        path: path.join(outDir, `m${String(i).padStart(6, "0")}.png`),
        omitBackground: true,
      });
    }
    await page.close();
    return { pattern: path.join(outDir, "m%06d.png"), frames: total, fps: sampleRate };
  } catch {
    return null;
  } finally {
    await browser.close().catch(() => {});
  }
}
