/**
 * Motion that is designed, not filtered.
 *
 * Everything else in this renderer asks ffmpeg to move pixels around. That is
 * the right tool for a push, a crop or a colour shift, and the wrong one for
 * type that arrives with weight — a word that overshoots and settles, letters
 * that stagger in, a card that lands. Those are described far more naturally in
 * HTML and CSS than in a filter expression, and CSS has an easing model that
 * `zoompan` does not.
 *
 * So a scene is a web page, and this module turns it into a transparent frame
 * sequence that the main graph lays over the video.
 *
 * **Nothing is ever played.** Every animation on the page is paused, and for
 * frame N the page is *seeked* to N/fps and screenshotted. A frame therefore
 * takes as long as it takes to paint — a second, a minute — and comes out
 * identical either way. Render the same scene twice and the bytes match, which
 * is the property that separates a motion engine from a screen recorder, and
 * the one the test asserts.
 *
 * Two mistakes are worth naming because both cost a day:
 *
 * - Playwright's `screenshot({ animations: "disabled" })` does not freeze
 *   animations, it **fast-forwards them to their end**. With time already being
 *   driven by hand it silently renders every frame as the last one.
 * - `cubic-bezier` cannot overshoot and settle, which is the whole character of
 *   a spring. So the curve is generated by sampling a damped oscillator and
 *   emitted as CSS `linear()`.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

/** Samples per output frame. Four is enough for a convincing shutter. */
export const MOTION_SUBSAMPLES = 4;

/**
 * A damped oscillator, sampled into a CSS `linear()` curve.
 *
 * `damping` is how fast it stops arguing with itself and `frequency` how many
 * times it argues. 7.2 and 10.5 give one clear overshoot and a quick settle,
 * which reads as "solid object" rather than "bouncy toy".
 */
export function spring(damping = 7.2, frequency = 10.5, samples = 60): string {
  const points: string[] = [];
  for (let i = 0; i <= samples; i += 1) {
    const t = i / samples;
    const value = 1 - Math.exp(-damping * t) * Math.cos(frequency * t);
    points.push(value.toFixed(5));
  }
  // The last sample must be exactly 1 or the element settles a hair off its
  // final position and stays there.
  points[points.length - 1] = "1";
  return `linear(${points.join(",")})`;
}

export interface MotionTitle {
  text: string;
  /** Seconds on the *output* clock. The caller has already remapped it. */
  at: number;
  durationSeconds: number;
  style: "card" | "lower-third" | "word";
  position: "top" | "center" | "bottom";
}

export interface MotionSceneOptions {
  width: number;
  height: number;
  fps: number;
  titles: MotionTitle[];
  /** Total length of the layer, in seconds. */
  durationSeconds: number;
}

const PLACEMENT: Record<MotionTitle["position"], string> = {
  top: "align-items:flex-start;padding-top:12%",
  center: "align-items:center",
  bottom: "align-items:flex-end;padding-bottom:18%",
};

/**
 * The scene, as a self-contained page.
 *
 * Written as one document with one animation per title rather than a timeline
 * abstraction: the browser already has a timeline, and every layer of
 * indirection over it is a layer that can disagree with what is drawn.
 */
export function sceneHtml(options: MotionSceneOptions): string {
  const { width, height, titles } = options;
  const curve = spring();

  const blocks = titles
    .map((title, index) => {
      const cls = `t${index}`;
      const size = title.style === "card" ? 0.11 : title.style === "lower-third" ? 0.062 : 0.135;
      const weight = title.style === "word" ? 900 : 800;
      // Escaped here rather than trusted: a title is user text, and a page is a
      // place where user text becomes markup if nobody stops it.
      const safe = title.text
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
      return {
        css: `
        .${cls} {
          position:absolute; inset:0; display:flex; justify-content:center;
          ${PLACEMENT[title.position]};
          opacity:0;
          animation: in-${cls} 620ms ${curve} ${title.at}s forwards,
                     out-${cls} 320ms ease-in ${(title.at + title.durationSeconds).toFixed(3)}s forwards;
        }
        .${cls} span {
          font: ${weight} ${Math.round(height * size)}px/1.1 Inter, "DejaVu Sans", system-ui, sans-serif;
          color:#fff; text-align:center; max-width:82%;
          letter-spacing:-0.02em;
          text-shadow: 0 ${Math.round(height * 0.004)}px ${Math.round(height * 0.012)}px rgba(0,0,0,.55);
          transform: translateY(${Math.round(height * 0.05)}px) scale(.94);
          animation: rise-${cls} 620ms ${curve} ${title.at}s forwards;
        }
        @keyframes in-${cls} { to { opacity:1 } }
        @keyframes out-${cls} { to { opacity:0 } }
        @keyframes rise-${cls} { to { transform: translateY(0) scale(1) } }`,
        html: `<div class="${cls}"><span>${safe}</span></div>`,
      };
    });

  return `<!doctype html><html><head><meta charset="utf-8"><style>
  html,body { margin:0; padding:0; width:${width}px; height:${height}px; background:transparent; overflow:hidden }
  ${blocks.map((b) => b.css).join("\n")}
  </style></head><body>${blocks.map((b) => b.html).join("")}</body></html>`;
}

export interface MotionLayer {
  /** ffmpeg input pattern for the frame sequence, e.g. `/tmp/x/m%06d.png`. */
  pattern: string;
  frames: number;
  fps: number;
}

/**
 * Render the scene to a transparent PNG sequence.
 *
 * Returns `null` when no browser is available, which is a real case — the
 * worker image carries one, a laptop running the suite may not — and a missing
 * browser must cost the titles, not the render.
 */
export async function renderMotionLayer(
  options: MotionSceneOptions,
  outDir: string,
): Promise<MotionLayer | null> {
  let chromium: typeof import("playwright-core")["chromium"];
  try {
    ({ chromium } = require("playwright-core"));
  } catch {
    return null;
  }

  const executablePath = process.env["CHROMIUM_PATH"] ?? "/usr/bin/chromium";
  let browser;
  try {
    browser = await chromium.launch({
      executablePath,
      args: ["--no-sandbox", "--force-color-profile=srgb", "--disable-lcd-text"],
    });
  } catch {
    return null;
  }

  try {
    await mkdir(outDir, { recursive: true });
    const html = path.join(outDir, "scene.html");
    await writeFile(html, sceneHtml(options), "utf8");

    const page = await browser.newPage({
      viewport: { width: options.width, height: options.height },
      deviceScaleFactor: 1,
    });
    await page.goto(`file://${html}`, { waitUntil: "load" });
    // Fonts must resolve before the first frame or frame 0 renders in a
    // fallback face and every later frame renders in the real one — a seam
    // nobody would guess at from the code.
    await page.evaluate(() => document.fonts.ready);

    const sampleRate = options.fps * MOTION_SUBSAMPLES;
    const total = Math.ceil(options.durationSeconds * sampleRate);
    for (let i = 0; i < total; i += 1) {
      const timeMs = (i / sampleRate) * 1000;
      await page.evaluate((t) => {
        for (const animation of document.getAnimations()) {
          animation.pause();
          animation.currentTime = t;
        }
      }, timeMs);
      await page.screenshot({
        path: path.join(outDir, `m${String(i).padStart(6, "0")}.png`),
        omitBackground: true,
      });
    }
    await page.close();
    return { pattern: path.join(outDir, "m%06d.png"), frames: total, fps: sampleRate };
  } catch {
    return null;
  } finally {
    await browser.close().catch(() => {});
  }
}
