/**
 * The capability table, as a page somebody can read.
 *
 * `inventory.mjs` answers the question in a terminal, which is the right place
 * for CI and the wrong place for the conversation Osama asked for — reviewing
 * each thing, measuring it, and deciding what to improve. This renders the
 * same data as a page.
 *
 * Generated, for the same reason the table is: a hand-written page about what
 * the product does is a page that was true the day it was written. Regenerating
 * it is one command, so it can be republished whenever anything ships and it
 * cannot quietly disagree with the code.
 *
 * Usage: node tools/inventory-page.mjs > out.html
 */
import { spawnSync } from "node:child_process";

const result = spawnSync("node", ["tools/inventory.mjs", "--json"], { encoding: "utf8" });
if (result.status !== 0) {
  console.error(result.stderr || "inventory failed");
  process.exit(1);
}
const data = JSON.parse(result.stdout);

const escape = (s) =>
  String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);

/** A count, coloured by whether it is a number anybody should worry about. */
const cover = (n) => {
  const band = n === 0 ? "none" : n <= 3 ? "thin" : "ok";
  return `<td class="num ${band}">${n}</td>`;
};

const DOOR = {
  button: "زرّ قالب",
  sentence: "جملة",
  server: "الخادم",
  none: "لا شيء",
};

const operations = data.operations
  .map(
    (op) => `      <tr>
        <td class="name">${escape(op.operation)}</td>
        <td class="purpose">${escape(op.purpose)}</td>
        <td class="mark">${op.renderer ? "✓" : "·"}</td>
        <td class="mark">${op.keywords ? "✓" : "·"}</td>
        <td class="mark">${op.conditional ? "~" : op.model ? "✓" : "·"}</td>
        ${cover(op.templates.length)}
        ${cover(op.suites.length)}
        <td class="door door-${op.door}">${DOOR[op.door] ?? op.door}</td>
      </tr>`,
  )
  .join("\n");

const areas = data.areas
  .slice()
  .sort((a, b) => b.endpoints.length - a.endpoints.length)
  .map(
    (area) => `      <tr>
        <td class="name">${escape(area.file)}</td>
        <td class="purpose">${escape(area.purpose)}</td>
        <td class="num ok">${area.endpoints.length}</td>
        ${cover(area.suites.length)}
      </tr>`,
  )
  .join("\n");

const worker = data.worker
  .slice()
  .sort((a, b) => b.suites.length - a.suites.length || a.file.localeCompare(b.file))
  .map(
    (part) => `      <tr>
        <td class="name">${escape(part.file)}</td>
        ${
          part.suites.length > 0
            ? cover(part.suites.length)
            : `<td class="num through">عبر ${escape(part.through.slice(0, 2).join("، "))}</td>`
        }
      </tr>`,
  )
  .join("\n");

const holes =
  data.holes.length === 0
    ? `<p class="clean">لا ثغرات: كل عملية مبنيّة، ويمكن الوصول إليها، والمخطِّطان متّفقان عليها، ومغطّاة بفحص.</p>`
    : `<ul class="holes">${data.holes
        .map((h) => `<li><b>${escape(h.operation)}</b> — ${escape(h.kind)}<br><span>${escape(h.why)}</span></li>`)
        .join("")}</ul>`;

const totalEndpoints = data.areas.reduce((n, a) => n + a.endpoints.length, 0);

process.stdout.write(`<title>ما تفعله Editly</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
  /*
    Generated by tools/inventory-page.mjs — do not edit by hand. Every number
    below is read out of the code, so the page cannot disagree with the product
    unless the reader is looking at an old copy of it.
  */
  :root {
    color-scheme: dark;
    --ground: #0a090c;
    --raised: #100e14;
    --row: #0d0b11;
    --line: #221f2b;
    --line-soft: #191722;
    --ink: #f7f6f9;
    --ink-dim: #a49fb0;
    --ink-faint: #6f6a7d;
    --accent: #6c3bff;
    --accent-soft: #9b6bff;
    --good: #35c98a;
    --warn: #e0a52e;
    --stop: #e5484d;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; background: var(--ground); color: var(--ink);
    font-family: "IBM Plex Sans Arabic", "Segoe UI", system-ui, sans-serif;
    font-size: 15px; line-height: 1.7; direction: rtl;
    -webkit-font-smoothing: antialiased;
  }
  .page { max-width: 1000px; margin: 0 auto; padding: 52px 20px 88px; }
  .eyebrow { font-size: 11px; font-weight: 600; letter-spacing: 0.14em; text-transform: uppercase; color: var(--accent-soft); margin: 0 0 12px; direction: ltr; text-align: right; }
  h1 { font-size: clamp(26px, 5vw, 36px); line-height: 1.25; margin: 0 0 12px; text-wrap: balance; }
  .standfirst { color: var(--ink-dim); margin: 0 0 8px; max-width: 64ch; }
  .generated { font-size: 13px; color: var(--ink-faint); margin: 0 0 40px; }
  .generated code { font-family: "IBM Plex Mono", monospace; font-size: 12px; background: rgba(255,255,255,0.05); padding: 1px 6px; border-radius: 5px; direction: ltr; display: inline-block; }
  h2 { font-size: 19px; margin: 46px 0 6px; padding-top: 22px; border-top: 1px solid var(--line-soft); }
  h2:first-of-type { border-top: none; padding-top: 0; }
  .note { color: var(--ink-faint); font-size: 14px; margin: 0 0 18px; max-width: 66ch; }

  .scroll { overflow-x: auto; border: 1px solid var(--line); border-radius: 12px; }
  table { border-collapse: collapse; width: 100%; min-width: 640px; }
  th {
    background: var(--raised); text-align: right; font-size: 11px; font-weight: 600;
    letter-spacing: 0.06em; text-transform: uppercase; color: var(--ink-faint);
    padding: 11px 12px; border-bottom: 1px solid var(--line); white-space: nowrap;
  }
  td { padding: 10px 12px; border-bottom: 1px solid var(--line-soft); vertical-align: middle; }
  tr:last-child td { border-bottom: none; }
  tr:nth-child(even) td { background: var(--row); }
  .name { font-family: "IBM Plex Mono", monospace; font-size: 13px; direction: ltr; text-align: right; white-space: nowrap; }
  .purpose { color: var(--ink-dim); font-size: 14px; }
  .mark, .num { text-align: center; font-variant-numeric: tabular-nums; width: 62px; }
  .mark { color: var(--good); font-size: 15px; }
  .num.ok { color: var(--ink-dim); }
  .num.thin { color: var(--warn); }
  .num.none { color: var(--stop); font-weight: 700; }
  .num.through { color: var(--ink-faint); font-size: 12px; width: auto; text-align: right; }
  .door { font-size: 12.5px; white-space: nowrap; width: 92px; }
  .door-button { color: var(--accent-soft); }
  .door-sentence { color: var(--ink-dim); }
  .door-server { color: var(--ink-faint); }
  .door-none { color: var(--stop); }

  .legend { font-size: 13px; color: var(--ink-faint); margin: 12px 0 0; }
  .clean { color: var(--good); font-size: 15px; border: 1px solid rgba(53,201,138,0.25); background: rgba(53,201,138,0.07); border-radius: 12px; padding: 14px 18px; margin: 0; }
  .holes { list-style: none; padding: 0; margin: 0; }
  .holes li { border: 1px solid rgba(229,72,77,0.3); background: rgba(229,72,77,0.06); border-radius: 12px; padding: 14px 18px; margin-bottom: 10px; }
  .holes span { color: var(--ink-dim); font-size: 14px; }
  .foot { margin-top: 52px; padding-top: 18px; border-top: 1px solid var(--line); font-size: 13px; color: var(--ink-faint); }
</style>

<div class="page">
  <p class="eyebrow">Editly · capability inventory</p>
  <h1>ما تفعله المنصّة، مقروءًا من الكود</h1>
  <p class="standfirst">
    كل رقم في هذه الصفحة حقيقة عن ملفّ، لا سطر كتبه أحد. جدول مكتوب بيد يكون
    صحيحًا يوم كُتب ثم ينحرف بصمت؛ هذا يُولَّد، فلا يستطيع أن يخالف المنتج.
  </p>
  <p class="generated">
    يُعاد توليدها بـ<code>node tools/inventory-page.mjs</code>، وCI يشغّل
    <code>node tools/inventory.mjs --check</code> على كل دفعة فيسقط البناء إن ظهرت ثغرة.
  </p>

  <h2>عمليات المونتاج — ${data.operations.length}</h2>
  <p class="note">
    <b>مبنيّة</b> أن للعامل فرعًا ينفّذها · <b>جملة</b> أن مطابق الكلمات يستطيع
    إنتاجها · <b>نموذج</b> أنها في المفردات التي يُعطاها المخطِّط ·
    <b>قوالب</b> كم قالبًا يستعملها · <b>فحوص</b> كم سويتة تسمّيها ·
    <b>الباب</b> كيف يصل إليها إنسان.
  </p>
  <div class="scroll">
    <table>
      <thead><tr>
        <th>العملية</th><th>ماذا تفعل</th><th>مبنيّة</th><th>جملة</th><th>نموذج</th><th>قوالب</th><th>فحوص</th><th>الباب</th>
      </tr></thead>
      <tbody>
${operations}
      </tbody>
    </table>
  </div>
  <p class="legend">~ = في مفردات النموذج فقط حين يملك المشروع ملفًّا من ذلك النوع.</p>

  <h2>بقيّة المنتج — ${data.areas.length} مجالًا، ${totalEndpoints} نقطة</h2>
  <p class="note">
    العمليات هي الحرفة وليست كل الأداة: هناك أيضًا التسجيل والرفع والدفع
    والجدولة والخطوط ولوحة التشغيل. مجالٌ بلا فحص هو جزء من المنتج لا أحد
    يلاحظ توقّفه.
  </p>
  <div class="scroll">
    <table>
      <thead><tr><th>الملفّ</th><th>ماذا يفعل</th><th>نقاط</th><th>فحوص</th></tr></thead>
      <tbody>
${areas}
      </tbody>
    </table>
  </div>

  <h2>العامل — ${data.worker.length} وحدة</h2>
  <p class="note">
    العامل نصف المنتج ولا يجيب على HTTP. التغطية تُحسب بمسار الملفّ، وبقفزة
    واحدة لمن تستورده وحدة مغطّاة — لأن <code>render-test</code> يحزم
    <code>ffmpeg.ts</code> وتمرّ كل تأكيداته عبر ما يستورده.
  </p>
  <div class="scroll">
    <table>
      <thead><tr><th>الوحدة</th><th>فحوص</th></tr></thead>
      <tbody>
${worker}
      </tbody>
    </table>
  </div>

  <h2>الثغرات</h2>
  <p class="note">
    أربعة أنواع تُفحص كل دفعة: عملية في العقد بلا فرع في العامل · عملية مبنيّة
    لا يستطيع أحد طلبها · عملية يختلف عليها المخطِّطان (فيتغيّر سلوك المنتج
    بحسب وجود مفتاح) · وشيء لا تسمّيه أي سويتة.
  </p>
  ${holes}

  <p class="foot">
    ${data.suites.length} سويتة · ${data.templates.length} قوالب · وُلّدت في ${new Date().toISOString().slice(0, 10)}
  </p>
</div>
`);
